USE [master]
GO

/****** Object:  Database [futureShop]    Script Date: 2017/7/24 18:54:42 ******/
CREATE DATABASE [futureShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'futureShop_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\futureShop_Data.mdf' , SIZE = 8320KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'futureShop_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\futureShop_Log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [futureShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [futureShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [futureShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [futureShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [futureShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [futureShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [futureShop] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [futureShop] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [futureShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [futureShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [futureShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [futureShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [futureShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [futureShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [futureShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [futureShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [futureShop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [futureShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [futureShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [futureShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [futureShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [futureShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [futureShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [futureShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [futureShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [futureShop] SET  MULTI_USER 
GO

ALTER DATABASE [futureShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [futureShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [futureShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [futureShop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [futureShop] SET  READ_WRITE 
GO

